import {position} from '@shopify/restyle';

export const Assets = {
  Common: {
    background: require('./common/New-Background.png'),
  },
  Auth: {
    logo: require('./auth/SoccerLogo.png'),
    Splash: require('./auth/Splashlogo.gif'),
  },
  Home: {
    Hrs_Per_goal: require('./home/Asset_5_4x.webp'),
    PlayerLogin: require('./home/Asset_6_4x.webp'),
    Password: require('./home/Password.png'),
    fastest_goal: require('./home/Artboard1.png'),
    Players_Duration: require('./home/Asset_7_4x.webp'),
    navHome: require('./home/Asset79173.png'),
    Add: require('./home/Asset80173.png'),
    Awards: require('./home/Asset_10_4x.webp'),
    Like: require('./home/Asset_11_4x.webp'),
    Notify: require('./home/Asset_12_4x.webp'),
    BackgroundCircle: require('./home/Asset_13_4x.webp'),
    icons10: require('./home/Asset_14_4x.webp'),
    jersy: require('./home/Asset_15_4x.webp'),
    jersy2: require('./home/newBg.png'),
    Defense: require('./home/Asset_25_4x.webp'),
    Defense_Background: require('./home/Asset_17_1.5x.webp'),
    Border_Frame: require('./home/Asset_18_4x.webp'),
    Tshirt_logo: require('./home/SouthThalaivas.webp'),
    Banglore: require('./home/BangaloreIndians.webp'),
    Bhopal: require('./home/BhopalTitans.webp'),
    Header1: require('./home/Asset_19_4x.webp'),
    Header2: require('./home/Asset_20_4x.webp'),
    Header3: require('./home/Asset_21_4x.webp'),
    Upcoming: require('./home/Asset_22_4x.webp'),
    EndMatch: require('./home/Asset_23_4x.webp'),
    Live: require('./home/Asset_24_4x.webp'),
    win: require('./home/winImg.png'),
    loss: require('./home/lossImg.png'),
    Field: require('./home/ground.png'),
    AttackLabel: require('./home/AttackLabel.png'),
    MidfieldLabel: require('./home/MidfieldLabel.png'),
    DefenceLabel: require('./home/DefenseLabel.png'),
    GoalKeeper: require('./home/GoalkeeperBlue.gif'),
    GoalKeeper1: require('./home/GoalkeeperRed.gif'),
    Movement: require('./home/Notificationgoal.png'),
    ScoreBoard: require('./home/Scoreboardborder.png'),
    ScoreBoard1: require('./home/Scoreboardborder1.png'),
    Draw: require('./home/drawImg.png'),
    PlayerPosition: require('./home/PlayerPosition.png'),
    PlayerPosition1: require('./home/PlayerPositionblue.gif'),
  },
  Uploads: {
    prescription: require('./uploads/Asset_2_1.5x.webp'),
    Camps: require('./uploads/Asset_3_1.5x.webp'),
    POB: require('./uploads/Asset_4_1.5x.webp'),
    conversion: require('./uploads/Asset_5_1.5x.webp'),
    more: require('./uploads/Asset_6_1.5x.webp'),
  },

  PlayerPosition: {
    1: [
      require('./PlayerPosition/10.gif'),
      require('./PlayerPosition/11.gif'),
      require('./PlayerPosition/12.gif'),
      require('./PlayerPosition/13.gif'),
      require('./PlayerPosition/14.gif'),
    ],
    2: [
      require('./PlayerPosition/Defense0.gif'),
      require('./PlayerPosition/Defense1.gif'),
      require('./PlayerPosition/Defense1.gif'),
      require('./PlayerPosition/Defense1.gif'),
      require('./PlayerPosition/Defense1.gif'),
    ],
    3: [
      require('./PlayerPosition/goal0.gif'),
      require('./PlayerPosition/goal1.gif'),
      require('./PlayerPosition/goal2.gif'),
      require('./PlayerPosition/goal3.gif'),
      require('./PlayerPosition/goal4.gif'),
    ],
    4: [
      require('./PlayerPosition/Gif40.gif'),
      require('./PlayerPosition/Gif41.gif'),
      require('./PlayerPosition/Gif42.gif'),
      require('./PlayerPosition/Gif43.gif'),
      require('./PlayerPosition/Gif44.gif'),
    ],
    5: [
      require('./PlayerPosition/MidField50.gif'),
      require('./PlayerPosition/MidField51.gif'),
      require('./PlayerPosition/MidField52.gif'),
      require('./PlayerPosition/MidField53.gif'),
      require('./PlayerPosition/MidField54.gif'),
    ],
    6: [
      require('./PlayerPosition/Attack_60.gif'),
      require('./PlayerPosition/Attack_61.gif'),
      require('./PlayerPosition/Attack_62.gif'),
      require('./PlayerPosition/Attack_63.gif'),
      require('./PlayerPosition/Attack_64.gif'),
    ],
    7: [
      require('./PlayerPosition/attack70.gif'),
      require('./PlayerPosition/attack71.gif'),
      require('./PlayerPosition/attack72.gif'),
      require('./PlayerPosition/attack73.gif'),
      require('./PlayerPosition/attack74.gif'),
    ],
  },
  PlayerMoves: {
    MyTeam: {
      ATTACK: [
        require('./PlayerMoves/Red1.gif'),
        require('./PlayerMoves/Red2.gif'),
        require('./PlayerMoves/Red3.gif'),
        require('./PlayerMoves/Red4.gif'),
        require('./PlayerMoves/Red5.gif'),
        require('./PlayerMoves/Red6.gif'),
        require('./PlayerMoves/Red7.gif'),
        require('./PlayerMoves/Red8.gif'),
        require('./PlayerMoves/Red9.gif'),
        require('./PlayerMoves/Red10.gif'),
      ],

      MIDFIELD: [
        require('./PlayerMoves/Red11.gif'),
        require('./PlayerMoves/Red12.gif'),
        require('./PlayerMoves/Red13.gif'),
        require('./PlayerMoves/Red14.gif'),
        require('./PlayerMoves/Red15.gif'),
        require('./PlayerMoves/Red16.gif'),
        require('./PlayerMoves/Red17.gif'),
        require('./PlayerMoves/Red18.gif'),
        require('./PlayerMoves/Red19.gif'),
        require('./PlayerMoves/Red20.gif'),
        require('./PlayerMoves/Red21.gif'),
        require('./PlayerMoves/Red22.gif'),
      ],

      DEFENSE: [
        require('./PlayerMoves/Red23.gif'),
        require('./PlayerMoves/Red24.gif'),
        require('./PlayerMoves/Red25.gif'),
        require('./PlayerMoves/Red26.gif'),
        require('./PlayerMoves/Red26.gif'),
        require('./PlayerMoves/Red27.gif'),
        require('./PlayerMoves/Red28.gif'),
        require('./PlayerMoves/Red29.gif'),
        require('./PlayerMoves/Red30.gif'),
        require('./PlayerMoves/Red31.gif'),
        require('./PlayerMoves/Red32.gif'),
      ],
    },

    OppTeam: {
      ATTACK: [
        require('./PlayerMoves/Blue1.gif'),
        require('./PlayerMoves/Blue2.gif'),
        require('./PlayerMoves/Blue3.gif'),
        require('./PlayerMoves/Blue4.gif'),
        require('./PlayerMoves/Blue5.gif'),
        require('./PlayerMoves/Blue6.gif'),
        require('./PlayerMoves/Blue7.gif'),
        require('./PlayerMoves/Blue8.gif'),
        require('./PlayerMoves/Blue9.gif'),
        require('./PlayerMoves/Blue10.gif'),
      ],

      MIDFIELD: [
        require('./PlayerMoves/Blue11.gif'),
        require('./PlayerMoves/Blue12.gif'),
        require('./PlayerMoves/Blue13.gif'),
        require('./PlayerMoves/Blue14.gif'),
        require('./PlayerMoves/Blue15.gif'),
        require('./PlayerMoves/Blue16.gif'),
        require('./PlayerMoves/Blue17.gif'),
        require('./PlayerMoves/Blue18.gif'),
        require('./PlayerMoves/Blue19.gif'),
        require('./PlayerMoves/Blue20.gif'),
        require('./PlayerMoves/Blue21.gif'),
        require('./PlayerMoves/Blue22.gif'),
      ],

      DEFENSE: [
        require('./PlayerMoves/Blue23.gif'),
        require('./PlayerMoves/Blue24.gif'),
        require('./PlayerMoves/Blue25.gif'),
        require('./PlayerMoves/Blue26.gif'),
        require('./PlayerMoves/Blue27.gif'),
        require('./PlayerMoves/Blue28.gif'),
        require('./PlayerMoves/Blue29.gif'),
        require('./PlayerMoves/Blue30.gif'),
        require('./PlayerMoves/Blue31.gif'),
        require('./PlayerMoves/Blue32.gif'),
      ],
    },
  },
};
